import hashlib
import json
import logging
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from dotenv import load_dotenv

try:
    import certifi
    from pymongo import MongoClient
except ImportError:
    certifi = None
    MongoClient = None

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# Load env
load_dotenv()


def load_json_or_jsonl(path: Path) -> Any:
    """Load JSON or JSONL while tolerating empty/invalid lines in JSONL files."""
    if path.suffix.lower() == ".jsonl":
        rows = []
        with open(path, "r", encoding="utf-8") as f:
            for line_no, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError as exc:
                    logger.warning(f"Skipping malformed JSONL line {line_no} in {path}: {exc}")
        return rows

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def flatten_history_data(data: Any) -> Any:
    """Convert product_id keyed history dicts into Mongo-friendly documents."""
    if isinstance(data, dict):
        return [{"product_id": str(product_id), "history": history} for product_id, history in data.items()]
    return data


def history_sources_for_shop(shop_name: str) -> Dict[Path, str]:
    """Return history files generated by track_history.py and their collection suffixes."""
    base_dir = Path("data")
    return {
        base_dir / "price_history" / f"{shop_name}.json": "_history_price",
        base_dir / "availability_history" / f"{shop_name}.json": "_history_availability",
        base_dir / "products_added" / f"{shop_name}.json": "_products_added",
        base_dir / "products_removed" / f"{shop_name}.json": "_products_removed",
    }


# Shops that go to the new (second) MongoDB cluster instead of the default.
NEW_DB_SHOPS = {"tunewtec", "gamershop", "megapc", "yatoo", "affariyet", "chaktech", "techland", "bstech", "drest", "lamode"}


def _shop_from_collection(collection_name: str) -> str:
    """Return the shop slug from a collection name like 'tunewtec_products'."""
    if not collection_name:
        return ""
    return collection_name.split("_", 1)[0]


def _is_quota_error(exc: Exception) -> bool:
    """Detect MongoDB Atlas free-tier quota errors."""
    msg = str(exc).lower()
    if (
        "over your space quota" in msg
        or "writes are blocked" in msg
        or ("quota" in msg and "atlas" in msg)
    ):
        return True
    # Atlas free-tier shows code 8000 AtlasError when over quota
    code = getattr(exc, "code", None)
    if code == 8000 and "atlas" in msg:
        return True
    return False


class MongoDBExporter:
    def __init__(self):
        self.local_uri = os.getenv("MONGO_URI_LOCAL") or os.getenv("MONGO_URI_lslsl")
        self.atlas_uri = os.getenv("MONGO_URI")
        self.atlas_uri_new = os.getenv("MONGO_URI_NEW")
        self.db_name = os.getenv("MONGO_DB_NAME", "Retails")
        self.db_name_new = os.getenv("MONGO_DB_NAME_NEW", "Retails")

        # clients is a list of (name, client, db_name, accepts_shop_fn)
        # accepts_shop_fn(shop) returns True if this client should handle that shop.
        self.clients = []
        # Direct ref to the new-cluster client (used as quota-fallback).
        self._fallback_client = None
        self._fallback_db_name = None
        # Once primary cluster is known to be over quota, route all subsequent
        # writes for that cluster directly to the fallback. Avoids per-write
        # quota probing and connection-closed cascades.
        self._primary_over_quota = False

        if MongoClient is None:
            logger.warning(
                "MongoDB export dependencies are not installed; install pymongo[srv] to enable database export."
            )
            return

        # Connect Local
        if self.local_uri:
            try:
                client = MongoClient(self.local_uri, serverSelectionTimeoutMS=2000)
                client.server_info()
                self.clients.append(("local", client, self.db_name, lambda s: True))
                logger.info(f"✅ Connected to Local MongoDB")
            except Exception as e:
                logger.warning(f"⚠️ Could not connect to Local MongoDB: {e}")

        # Connect Atlas (primary) — handles shops NOT in NEW_DB_SHOPS
        if self.atlas_uri:
            try:
                client = MongoClient(
                    self.atlas_uri,
                    serverSelectionTimeoutMS=5000,
                    tlsCAFile=certifi.where(),
                )
                client.server_info()
                self.clients.append((
                    "atlas",
                    client,
                    self.db_name,
                    lambda s: s not in NEW_DB_SHOPS,
                ))
                logger.info(f"✅ Connected to Atlas MongoDB (primary)")
            except Exception as e:
                logger.warning(f"⚠️ Could not connect to Atlas MongoDB: {e}")

        # Connect Atlas (new) — handles only shops in NEW_DB_SHOPS
        # ALSO acts as quota-fallback for the primary cluster.
        if self.atlas_uri_new:
            try:
                client = MongoClient(
                    self.atlas_uri_new,
                    serverSelectionTimeoutMS=5000,
                    tlsCAFile=certifi.where(),
                )
                client.server_info()
                self.clients.append((
                    "atlas-new",
                    client,
                    self.db_name_new,
                    lambda s: s in NEW_DB_SHOPS,
                ))
                # Save for quota-fallback use
                self._fallback_client = client
                self._fallback_db_name = self.db_name_new
                logger.info(f"✅ Connected to Atlas MongoDB (new — for {sorted(NEW_DB_SHOPS)} + quota fallback)")
            except Exception as e:
                logger.warning(f"⚠️ Could not connect to Atlas MongoDB (new): {e}")

        if not self.clients:
            logger.error("❌ No database connections available.")

    def close(self):
        for name, client, _db, _fn in self.clients:
            client.close()
            logger.info(f"Closed {name} connection")

    def _get_file_type(self, filename: str) -> str:
        if "summary" in filename:
            return "summary"
        if "products_detailed" in filename:
            return "products_detailed"
        if "categories" in filename:
            return "categories"
        if "merged" in filename:
            return "merged"
        if "products" in filename and "detailed" not in filename:
            return "products"
        return "other"

    def _get_shop_from_path(self, path: Path) -> str:
        parts = path.parts
        # data/mytek/2025...
        if "merged" in parts:
            return "merged"
        if "state" in parts:
            return "state"
        for p in parts:
            if p in [
                "mytek",
                "tunisianet",
                "technopro",
                "darty",
                "spacenet",
                "jumbo",
                "graiet",
                "batam",
                "zoom",
                "allani",
                "expert_gaming",
                "geant",
                "mapara",
                "parafendri",
                "parashop",
                "pharmacieplus",
                "pharmashop",
                "sbs",
                "scoop",
                "skymill",
                "wiki",
                "bestbuytunisie",
                "sigshop",
                "qsnet",
                "promouv",
                "bill",
                "techgate",
                "acspace",
                "krichen",
                "emh",
                "maalejaudio",
                "electrobennjima",
                "kamounhome",
                "agora",
                "tunewtec",
                "gamershop",
                "megapc",
                "yatoo",
                "affariyet",
                "chaktech",
                "techland",
                "bstech",
                "drest",
                "lamode",
            ]:
                return p
        return "unknown"

    def _write_to_db(self, db, collection_name: str, data, is_history: bool, is_changes: bool, now):
        """Perform the actual write to a database. Raises on failure."""
        from pymongo import UpdateOne
        coll = db[collection_name]

        if is_history:
            ops = []
            for d in data:
                if not isinstance(d, dict):
                    continue
                pid = d.get("product_id")
                if not pid:
                    continue
                d.setdefault("_updated_at", now)
                ops.append(UpdateOne(
                    {"product_id": str(pid)},
                    {"$set": d},
                    upsert=True,
                ))
            if ops:
                coll.bulk_write(ops, ordered=False)
            return ("upserted", len(ops))

        if is_changes:
            ops = []
            for d in data:
                if not isinstance(d, dict):
                    continue
                pid = d.get("product_id")
                detected_at = d.get("detected_at")
                if not pid or not detected_at:
                    continue
                d.setdefault("_updated_at", now)
                ops.append(UpdateOne(
                    {"product_id": str(pid), "detected_at": detected_at},
                    {"$setOnInsert": d},
                    upsert=True,
                ))
            if ops:
                coll.bulk_write(ops, ordered=False)
            return ("appended", len(ops))

        # Full replace for products / details / categories / summaries.
        coll.delete_many({})
        if isinstance(data, list):
            for d in data:
                if isinstance(d, dict):
                    d.setdefault("_updated_at", now)
            if data:
                # Chunk large inserts to avoid connection timeouts on big detail
                # collections (e.g. spacenet has 29K docs ≈ 80MB).
                CHUNK = 500
                for i in range(0, len(data), CHUNK):
                    coll.insert_many(data[i:i + CHUNK], ordered=False)
            return ("exported", len(data))
        elif isinstance(data, dict):
            data.setdefault("_updated_at", now)
            coll.insert_one(data)
            return ("exported", 1)
        return ("exported", 0)

    def export_collection(self, collection_name: str, data: List[Dict]):
        """
        Export documents to a collection.
        - History collections (_history_price, _history_availability): upsert by product_id,
          replacing the history array with the authoritative local version.
        - Change collections (_products_added, _products_removed): append-only by
          product_id + detected_at.
        - All other collections: full replace (delete all + insert all).

        If the primary Atlas cluster rejects a write due to free-tier quota, we
        automatically retry on the new (fallback) cluster so no data is lost.
        """
        if not data:
            return

        is_history = any(
            collection_name.endswith(s)
            for s in ("_history_price", "_history_availability")
        )
        is_changes = any(
            collection_name.endswith(s)
            for s in ("_products_added", "_products_removed")
        )

        shop = _shop_from_collection(collection_name)
        now = datetime.now()

        for name, client, db_name, accepts_shop in self.clients:
            if not accepts_shop(shop):
                continue

            # Sticky fallback: once primary Atlas is known to be over quota,
            # skip it entirely and route directly to atlas-new.
            if (
                name == "atlas"
                and self._primary_over_quota
                and self._fallback_client is not None
            ):
                try:
                    fb_db = self._fallback_client[self._fallback_db_name]
                    verb, count = self._write_to_db(
                        fb_db, collection_name, data, is_history, is_changes, now
                    )
                    logger.info(
                        f"  -> {verb.capitalize()} {count} items to '{collection_name}' on atlas-new (quota-routed)"
                    )
                except Exception as e:
                    logger.error(
                        f"  ❌ atlas-new (quota-routed) failed for '{collection_name}': {e}"
                    )
                continue

            db = client[db_name]
            try:
                verb, count = self._write_to_db(db, collection_name, data, is_history, is_changes, now)
                logger.info(f"  -> {verb.capitalize()} {count} items to '{collection_name}' on {name}")
            except Exception as e:
                # If the primary Atlas cluster is out of space, fall back to the new cluster.
                if (
                    name == "atlas"
                    and _is_quota_error(e)
                    and self._fallback_client is not None
                ):
                    self._primary_over_quota = True  # all future writes go to fallback
                    logger.warning(
                        f"  ⚠️ Primary Atlas over quota — falling back to atlas-new for '{collection_name}' (and all subsequent writes this run)"
                    )
                    try:
                        fb_db = self._fallback_client[self._fallback_db_name]
                        verb, count = self._write_to_db(
                            fb_db, collection_name, data, is_history, is_changes, now
                        )
                        logger.info(
                            f"  -> {verb.capitalize()} {count} items to '{collection_name}' on atlas-new (fallback)"
                        )
                    except Exception as e2:
                        logger.error(
                            f"  ❌ Fallback to atlas-new also failed for '{collection_name}': {e2}"
                        )
                else:
                    logger.error(
                        f"  ❌ Failed to export to '{collection_name}' on {name}: {e}"
                    )

    def _collection_for_path(self, path: Path) -> str:
        """Infer a collection name for ad hoc CLI exports."""
        filename = path.name.lower()
        parent = path.parent.name.lower()

        history_suffixes = {
            "price_history": "_history_price",
            "availability_history": "_history_availability",
            "products_added": "_products_added",
            "products_removed": "_products_removed",
        }
        if parent in history_suffixes:
            return f"{path.stem}{history_suffixes[parent]}"

        shop = self._get_shop_from_path(path)
        if "merged" in filename:
            return "merged_analytics" if "summary" in filename else "merged_products"
        if "products_detailed_summary" in filename:
            return f"{shop}_summary_details"
        if "products_summary" in filename:
            return f"{shop}_summary_products"
        if "products_detailed" in filename:
            return f"{shop}_details"
        if "categories" in filename:
            return f"{shop}_categories"
        if "products" in filename:
            return f"{shop}_products"
        if "summary" in filename:
            return f"{shop}_summary"
        return f"{shop}_other"

    def export_file(self, path: Path):
        """Export one JSON/JSONL file. Used by the CLI entrypoint."""
        if not path.exists():
            logger.error(f"File not found: {path}")
            return
        try:
            data = load_json_or_jsonl(path)
            if path.parent.name in {
                "price_history",
                "availability_history",
                "products_added",
                "products_removed",
            }:
                data = flatten_history_data(data)
            collection = self._collection_for_path(path)
            self.export_collection(collection, data)
        except Exception as e:
            logger.error(f"Failed to export file {path}: {e}")

    def export_directory(self, path: Path):
        """Export all JSON/JSONL files below a directory. Used by the CLI entrypoint."""
        if not path.exists():
            logger.error(f"Directory not found: {path}")
            return

        shop = self._get_shop_from_path(path)
        if shop != "unknown" and (path / "products.json").exists():
            self.export_shop_data(shop, path)
            return

        for fpath in sorted(path.rglob("*")):
            if fpath.suffix.lower() in {".json", ".jsonl"}:
                self.export_file(fpath)

    def export_shop_data(self, shop_name: str, latest_dir: Path):
        """
        Exports all relevant files for a shop to their respective collections.
        """
        logger.info(f"📦 Exporting full data for shop: {shop_name}")

        # Mapping: Filename -> Collection Suffix
        # e.g. products.json -> _products
        file_map = {
            "products.json": "_products",
            "products_detailed.json": "_details",
            "categories.json": "_categories",
            "products_summary.json": "_summary_products",
            "products_detailed_summary.json": "_summary_details",
        }

        for fname, suffix in file_map.items():
            fpath = latest_dir / fname
            if fpath.exists():
                try:
                    data = load_json_or_jsonl(fpath)
                    self.export_collection(f"{shop_name}{suffix}", data)
                except Exception as e:
                    logger.error(f"Failed to load {fname}: {e}")

        for fpath, suffix in history_sources_for_shop(shop_name).items():
            if fpath.exists():
                try:
                    data = flatten_history_data(load_json_or_jsonl(fpath))
                    self.export_collection(f"{shop_name}{suffix}", data)
                except Exception as e:
                    logger.error(f"Failed to export history {fpath.name}: {e}")


def export_latest_run():
    """Finds the latest run directories for each shop and exports them."""
    exporter = MongoDBExporter()
    if not exporter.clients:
        return

    base_dir = Path("data")
    shops = [
        "mytek",
        "tunisianet",
        "technopro",
        "darty",
        "spacenet",
        "jumbo",
        "graiet",
        "batam",
        "zoom",
        "allani",
        "expert_gaming",
        "geant",
        "mapara",
        "parafendri",
        "parashop",
        "pharmacieplus",
        "pharmashop",
        "sbs",
        "scoop",
        "skymill",
        "wiki",
        "bestbuytunisie",
        "sigshop",
        "qsnet",
        "promouv",
        "bill",
        "techgate",
        "acspace",
        "krichen",
        "emh",
        "maalejaudio",
        "electrobennjima",
        "kamounhome",
        "agora",
        "tunewtec",
        "gamershop",
        "megapc",
        "yatoo",
        "affariyet",
        "chaktech",
        "techland",
        "bstech",
        "drest",
        "lamode",
    ]

    # 1. Export Merged Data
    merged_dir = base_dir / "merged"
    if merged_dir.exists():
        logger.info("📦 Exporting Merged Data...")
        try:
            # Merged Products
            mp_path = merged_dir / "products_merged.json"
            if mp_path.exists():
                with open(mp_path, "r", encoding="utf-8") as f:
                    exporter.export_collection("merged_products", json.load(f))

            # Merged Summary
            ms_path = merged_dir / "products_merged_summary.json"
            if ms_path.exists():
                with open(ms_path, "r", encoding="utf-8") as f:
                    exporter.export_collection("merged_analytics", json.load(f))

        except Exception as e:
            logger.error(f"Failed merged export: {e}")

    # 2. Export Shop Data
    for shop in shops:
        shop_dir = base_dir / shop
        if shop_dir.exists():
            # Find latest timestamp dir (2025-12-22...)
            subdirs = []
            for d in shop_dir.iterdir():
                if d.is_dir() and d.name[0].isdigit() and "_" in d.name:
                    subdirs.append(d)

            subdirs.sort(key=lambda x: x.name, reverse=True)

            if subdirs:
                latest = subdirs[0]
                exporter.export_shop_data(shop, latest)

    exporter.close()


if __name__ == "__main__":
    # If args, export specific path, else export latest
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        exporter = MongoDBExporter()
        if path.is_file():
            exporter.export_file(path)
        elif path.is_dir():
            exporter.export_directory(path)
        exporter.close()
    else:
        export_latest_run()
